### ISSUE TITLE
No Screenshots - broken link

### ISSUE THREAD

**Issue by ProfRon** [sgaraud/gnome-extension-taskwarrior#2]
In your READNE.md, you have a link that apparently was meant to link to screenshots -- https://github.com/sgaraud/gnome-extension-taskwarrior/blob/master/taskwarriorgnomeshell.png?raw=true -- but that's a 404 broken link.

Which is a shame because there aren't any other screenshots I can find, either here at github or over at the gnome extensions page.  And since there is another TaskWarrior extension -- i.e. TaskWhisperer https://github.com/sgaraud/gnome-extension-taskwarrior/blob/master/taskwarriorgnomeshell.png?raw=true -- screenshots would be really useful, to help potential users (such as myself) see what's different with this extension, whether it would make sense to install it along side the other one, or instead of the other one, or not at all.... if you see what I mean.

**Comment by sgaraud** [comment]
Hello,

This is a good suggestion.
I will finish this up quickly. I was not even aware I had some competition
;-)
I develop that extension for my own workflow when in some cases the shell
access is not easy.
I will complete the readme tonight and probably update also the page on the
gnome-extensions website.

Thank you for your feedbacks,
Sylvain
