### ISSUE TITLE
Sort like "task next"

### ISSUE THREAD

**Issue by HeikoAdams** [sgaraud/gnome-extension-taskwarrior#4]
It would be helpful if the tasks are sorted like "task next" does.

**Comment by sgaraud** [comment]
Hello,
Currently the tasks are sorted based on urgency. But it is not limited to the 7 most urgent tasks like default next report. Is it what you want ? Just display the 7 most urgent tasks? Or did you make some custom modifications to the default next report ?

**Comment by HeikoAdams** [comment]
Sorry, my mistake. Everything's fine.
