### ISSUE TITLE
Doesn't seem to work on gnome 3.20

### ISSUE THREAD

**Issue by joopdo** [sgaraud/gnome-extension-taskwarrior#6]
Great idea for extension, but doesn't work.

**Comment by sgaraud** [comment]
add support to gnome 3.20 in commit e2bd949
tested with fedora 24 and ubuntu gnome using gnome 3.20.2 and 3.20.3.

**Comment by joopdo** [comment]
Actually randomly checked a few hours ago and noticed the change, you are awesome!
