### ISSUE TITLE
No Line Break with long task description on Multi Monitor setup

### ISSUE THREAD

**Issue by alinmear** [sgaraud/gnome-extension-taskwarrior#7]
Hey there. First thx for your great extension! 

**Setup**
I am heavily using taskwarrior for my task organisations and also documentation (via annotations). My setup: Fedora 24, Gnome 3.20 and 3 Monitors.

Monitor-Setup:
| LEFT-Monitor | CENTER-Monitor (Primary) | RIGHT-Monitor |

**Problem**
When there is a long task description the Window of your addon is spawning all over my main screen and the screen left of it because you raising the windows size with the task description length. Maybe limit the printed description and make linke breaks.

| LEFT-Monitor | CENTER-Monitor (Primary) | RIGHT-Monitor |
-------------------------------- WINDOW ----------|

**Comment by Weej1** [comment]
Hi, 
My issue matche the title description so I thought I'd just echo the request for some sort of word wrap function along with a vertical scrollbar. This is what my tasks currently look like: 
![screenshot from 2016-08-19 11-50-14](https://cloud.githubusercontent.com/assets/6381159/17800828/f1067226-6603-11e6-9785-5549fb7e6828.png)

making me not use the extension

**Comment by sgaraud** [comment]
Please thanks to give it a try and comment on the default line break value for the task description (120 chars)
